apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: three-tier-devops-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root123"
        - name: DB_NAME
          value: "employee_db"
        - name: DB_PORT
          value: "3306"
